### ISSUE TITLE
Orientation bug

### ISSUE THREAD

**Issue by s4ntiksu** [geode-sdk/android-launcher#14]
![Screenshot_20240127-205006](https://github.com/geode-sdk/android-launcher/assets/99120366/70d9ff51-d65a-4a18-9b99-8cba0abfa14f)
When launching the game from the launcher, it opens in portrait orientation, rebooting does not help.

**Comment by matcool** [comment]
impressive

**Comment by Fleeym** [comment]
try rotating your phone to landscape before launching as a temporary fix

**Comment by s4ntiksu** [comment]
> try rotating your phone to landscape before launching as a temporary fix

not working :/

**Comment by s4ntiksu** [comment]
There's something wrong with the game itself, everything works
