### ISSUE TITLE
fopen hook to change savefile path might not work sometimes, wiping save file

### ISSUE THREAD

**Issue by matcool** [geode-sdk/android-launcher#15]
this has happened to me exactly once, and its quite a rare bug, but it could happen if the entry point that does that hook is not blocking the gd thread, so it would be a race condition

maybe we should also do the hook in geode itself, for safety.

**Comment by qimiko** [comment]
linking geode-sdk/geode@0188eee5e57ba20f9dacefb9993f6b0b5cdf374d to this as a note
