### ISSUE TITLE
Geode crashes upon attempting to open Geometry Dash 2.205

### ISSUE THREAD

**Issue by XBladeXGMD** [geode-sdk/android-launcher#18]
Upon pressing launch on both geode launchers, screen goes black, Geode crashes, and Geometry Dash does not open.

Here is the log (from 32bit version)

00:35:19 INFO  [Main] [Geode]: Running Geode v2.0.0-beta.15
00:35:19 INFO  [Main] [Geode]: Setting up internal mod
00:35:19 INFO  [Main] [Geode]: Setting up loader
00:35:19 DEBUG [Main] [Geode]:   Loading launch arguments
00:35:19 DEBUG [Main] [Geode]:   Setting up crash handler
00:35:19 DEBUG [Main] [Geode]:   Loading hooks
00:35:19 DEBUG [Main] [Geode]:     Enabled cocos2d::CCFileUtils::fullPathForFilename hook at 0x8b744615 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled cocos2d::CCFileUtils::sharedFileUtils hook at 0x8b746419 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled __class_type_info::can_catch hook at 0x8b8a79c1 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled __dynamic_cast hook at 0x8b8a7a39 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled cocos2d::CCNode::getUserObject hook at 0x8b721d25 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled cocos2d::CCNode::setUserObject hook at 0x8b721fa7 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled LoadingLayer::init hook at 0x8b48d335 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled LoadingLayer::loadAssets hook at 0x8b48c8b1 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled MenuLayer::init hook at 0x8b48b901 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled AchievementNotifier::willSwitchToScene hook at 0x8b440bf7 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled AppDelegate::trySaveGame hook at 0x8b488989 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled FileOperation::getFilePath hook at 0x8b761285 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled cocos2d::CCScheduler::update hook at 0x8b714445 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled CCTextInputNode::ccTouchBegan hook at 0x8b47c9e1 for geode.loader
00:35:19 DEBUG [Main] [Geode]:     Enabled LoadingLayer::loadAssets hook at 0x8b48c8b1 for geode.loader
00:35:19 DEBUG [Main] [Geode]:   Setting up directories
00:35:19 INFO  [Main] [Geode]:   Refreshing mod graph
00:35:19 DEBUG [Main] [Geode]:     Queueing mods
00:35:19 DEBUG [Main] [Geode]:       Searching /storage/emulated/0/Android/media/com.geode.launcher/game/geode/mods
00:35:20 DEBUG [Main] [Geode]:     Populating mod list
00:35:20 DEBUG [Main] [Geode]:     Building mod graph
00:35:20 DEBUG [Main] [Geode]:       geode.loader
00:35:20 DEBUG [Main] [Geode]:     Loading early mods
00:35:20 INFO  [Main] [Geode]:     Took 0.001s. Continuing next frame...
00:35:20 DEBUG [Main] [Geode]: Setting up IPC
00:35:20 DEBUG [Main] [Geode]:   IPC is not supported on this platform!
00:35:20 INFO  [Main] [Geode]: Starting loader update check
00:35:20 INFO  [Main] [Geode]: Entry took 0.616s

**Comment by qimiko** [comment]
send crash dump, this is probably a geode issue and not launcher

**Comment by qimiko** [comment]
no crash dump :(
