### ISSUE TITLE
Geode Not compatible with Android 14

### ISSUE THREAD

**Issue by MalikHw** [geode-sdk/android-launcher#19]
I installed a gsi of Evolution X on my phone based on Android 14 but Geode won't work properly with it, if I open gd from it it crashes the whole phone

**Comment by matcool** [comment]
geode is indeed compatible with android 14.

**Comment by MalikHw** [comment]
Bruh then why it crashes on my case, maybe bcz it's on gsi?

**Comment by qimiko** [comment]
please send the application logs :(

**Comment by MalikHw** [comment]
Sorry but I have deleted Android 14
but It says everytime I open geode"this app is not optimized to work on
Android 14" what the f*** should I do?

**Comment by JOEYOCHO** [comment]
This sounds like you have a old nightly build of the launcher on 2.1 or smth

**Comment by MalikHw** [comment]
No I'm sure it's 2.2 and the updated launcher...

**Comment by qimiko** [comment]
you're using the 32bit version... but the application targets android 14
