### ISSUE TITLE
how do I see the ".log" in the Application Log? (Android32)

### ISSUE THREAD

**Issue by ElixirXDE** [geode-sdk/android-launcher#22]
### Your Question

I just want to know because that's where "No logs Available" comes out

![Screenshot_20240226-125619](https://github.com/geode-sdk/geode/assets/66583315/afd6cb3a-ca27-4045-8b53-cd54a60815f4)

**Comment by qimiko** [comment]
this is a launcher issue, so i've moved it there.

some devices have disabled logging (for whatever reason) and that's probably what happened here. please say what device and version of android you're using - it helps with debugging...

**Comment by ElixirXDE** [comment]
I was able to activate the Geode logs, I just went to the settings of my phone, then to developer options and I looked for something about a log buffer and left it at the maximum and so I activated the Geode logs :v
