### ISSUE TITLE
Android: Game does not start

### ISSUE THREAD

**Issue by lightyyt** [geode-sdk/android-launcher#25]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v2.0.0-beta.21

### Steps to Reproduce

Unknown. 

### Crash Report

[Geode 2024-03-04 00.44.16.log](https://github.com/geode-sdk/geode/files/14475085/Geode.2024-03-04.00.44.16.log)
[Geode 2024-03-04 00.35.32.log](https://github.com/geode-sdk/geode/files/14475086/Geode.2024-03-04.00.35.32.log)
[Geode 2024-03-04 00.46.19.log](https://github.com/geode-sdk/geode/files/14475087/Geode.2024-03-04.00.46.19.log)
[Geode 2024-03-04 00.43.59.log](https://github.com/geode-sdk/geode/files/14475088/Geode.2024-03-04.00.43.59.log)

### Additional Information

If giving my Device info helps: ZTE Blade V10 Vita running Android 9

**Comment by lightyyt** [comment]
Thank you for looking at it.

**Comment by qimiko** [comment]
can you try this version of the apk and see if it still crashes?
[app-universal-release.apk.zip](https://github.com/geode-sdk/android-launcher/files/14521701/app-universal-release.apk.zip)

**Comment by lightyyt** [comment]
It still crashes. The Game log still shows the same, and the app log is the same. heres a screenshot![Titelloses 100_20240307164325.png](https://github.com/geode-sdk/android-launcher/assets/75945595/ea67e90d-5df5-4539-b746-5949600cf5ed)

**Comment by qimiko** [comment]
hey if you're still having this issue can you try the build from the latest commit:
[geode-launcher-release.zip](https://github.com/geode-sdk/android-launcher/files/15020853/geode-launcher-release.zip)

it seems to have fixed the issue for someone else :slightly_smiling_face:

**Comment by lightyyt** [comment]
Thanks, it has now also worked for me. Thanks!

**Comment by qimiko** [comment]
fix should be in the latest launcher release now :)
