### ISSUE TITLE
Geode Launcher 1.4.0 or Geode 3.0.0 dosent start Geometry dash 2.206

### ISSUE THREAD

**Issue by ItalianNinjaa** [geode-sdk/android-launcher#29]
![Screenshot_20240622-232102_Geode](https://github.com/geode-sdk/android-launcher/assets/98443702/71dd9469-5b70-448e-a1c3-5fb466eba8a2)

I checked and I do have GD 2.206, but geode dosent start.

**Comment by matcool** [comment]
seems to be an issue specific to android 10

**Comment by ItalianNinjaa** [comment]
> seems to be an issue specific to android 10

I'm on android 10

**Comment by matcool** [comment]
I know

**Comment by VGDsAm** [comment]
Me pasa lo mismo.. Esperare actualización la vdd y ojalá lo solucionen.

**Comment by qimiko** [comment]
fixed in 70333e3b5f64055e4f3727f428ef3b7f2e700793

**Comment by VGDsAm** [comment]
Tiene solución el problema.. Me aparece lo mismo qué el de la imagen de arriba..

**Comment by VGDsAm** [comment]
Corrección ya esta solucionado jsjsjsj. 😁

Saludos! ⚡
