### ISSUE TITLE
Geode crashes on 2.2

### ISSUE THREAD

**Issue by NotTheCoderGb** [geode-sdk/android-launcher#4]
32 bits Android. Idk why it crashes :(

**Comment by TheSillyDoggo** [comment]
You just said why in the title... 2.2

**Comment by qimiko** [comment]
geode 2.2 is still in development so you probably have a build that isn't working, but please send the crash log anyways! (you can get it from running `adb logcat`)
please keep in mind this repo is exclusively for launcher issues

**Comment by matcool** [comment]
the launcher probably downloaded 1.4.0 geode automatically, which will not work in 2.2. and anyways as chloe said, this is not the correct repo
