### ISSUE TITLE
Library couldn't be find

### ISSUE THREAD

**Issue by Zlatovratsky** [geode-sdk/android-launcher#9]
![Screenshot_2024-01-19-20-59-50-80_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/geode-sdk/android-launcher/assets/153531337/9cac9a03-8fd4-40b2-92c8-38ab5d678a0f)

**Comment by qimiko** [comment]
please update your launcher! it's very likely that you've installed the 32bit version of geometry dash, which means you'll want to use the android32 version of the launcher

**Comment by qimiko** [comment]
closing this for now as there's been some updates since this issue was posted that probably resolve the issue. feel free to reopen if it still happens (with logs, please!)
